version: '3'
services:
  instance1:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 1001:1000
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USERNAME=your-redis-username
      - REDIS_PASSWORD=your-redis-password


  instance2:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 1002:1000
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USERNAME=your-redis-username
      - REDIS_PASSWORD=your-redis-password

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always

  nginx:
    image: nginx
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
